#
# Generated by omcli
# Cluster:dev.x2-4 Node:dev.x2-4.kafkacw-1
#
cat << 'OMHOST' > omhost
# Generated by omcli #omdb.omnode

192.168.10.21  dev.x2-4.kafka-1.ctrl-0       #omdb.omnode
192.168.104.2  dev.x2-4.kafka-1.ext-0        #omdb.omnode
192.168.214.2  dev.x2-4.kafka-1.ib-0         #omdb.omnode
192.168.204.2  dev.x2-4.kafka-1.int-0        #omdb.omnode
192.168.10.31  dev.x2-4.kafka-2.ctrl-0       #omdb.omnode
192.168.104.3  dev.x2-4.kafka-2.ext-0        #omdb.omnode
192.168.214.3  dev.x2-4.kafka-2.ib-0         #omdb.omnode
192.168.204.3  dev.x2-4.kafka-2.int-0        #omdb.omnode
192.168.10.41  dev.x2-4.kafka-3.ctrl-0       #omdb.omnode
192.168.104.4  dev.x2-4.kafka-3.ext-0        #omdb.omnode
192.168.214.4  dev.x2-4.kafka-3.ib-0         #omdb.omnode
192.168.204.4  dev.x2-4.kafka-3.int-0        #omdb.omnode
192.168.10.51  dev.x2-4.kafka-4.ctrl-0       #omdb.omnode
192.168.104.5  dev.x2-4.kafka-4.ext-0        #omdb.omnode
192.168.214.5  dev.x2-4.kafka-4.ib-0         #omdb.omnode
192.168.204.5  dev.x2-4.kafka-4.int-0        #omdb.omnode
192.168.10.11  dev.x2-4.kafkacw-1.ctrl-0     #omdb.omnode
192.168.104.1  dev.x2-4.kafkacw-1.ext-0      #omdb.omnode
192.168.10.11  dev.x2-4.kafkaui-1.ctrl-0     #omdb.omnode
192.168.104.1  dev.x2-4.kafkaui-1.ext-0      #omdb.omnode
192.168.10.61  dev.x2-4.kafkaw-1.ctrl-0      #omdb.omnode
192.168.104.6  dev.x2-4.kafkaw-1.ext-0       #omdb.omnode
192.168.10.71  dev.x2-4.kafkaw-2.ctrl-0      #omdb.omnode
192.168.104.7  dev.x2-4.kafkaw-2.ext-0       #omdb.omnode
192.168.10.11  dev.x2-4.minio-1.ctrl-0       #omdb.omnode
192.168.104.1  dev.x2-4.minio-1.ext-0        #omdb.omnode
192.168.10.21  dev.x2-4.rdp-1.ctrl-0         #omdb.omnode
192.168.104.2  dev.x2-4.rdp-1.ext-0          #omdb.omnode
192.168.214.2  dev.x2-4.rdp-1.ib-0           #omdb.omnode
192.168.204.2  dev.x2-4.rdp-1.int-0          #omdb.omnode
192.168.10.31  dev.x2-4.rdp-2.ctrl-0         #omdb.omnode
192.168.104.3  dev.x2-4.rdp-2.ext-0          #omdb.omnode
192.168.214.3  dev.x2-4.rdp-2.ib-0           #omdb.omnode
192.168.204.3  dev.x2-4.rdp-2.int-0          #omdb.omnode
192.168.10.41  dev.x2-4.rdp-3.ctrl-0         #omdb.omnode
192.168.104.4  dev.x2-4.rdp-3.ext-0          #omdb.omnode
192.168.214.4  dev.x2-4.rdp-3.ib-0           #omdb.omnode
192.168.204.4  dev.x2-4.rdp-3.int-0          #omdb.omnode
192.168.10.51  dev.x2-4.rdp-4.ctrl-0         #omdb.omnode
192.168.104.5  dev.x2-4.rdp-4.ext-0          #omdb.omnode
192.168.214.5  dev.x2-4.rdp-4.ib-0           #omdb.omnode
192.168.204.5  dev.x2-4.rdp-4.int-0          #omdb.omnode
192.168.10.11  dev.x2-4.rdpui-1.ctrl-0       #omdb.omnode
192.168.104.1  dev.x2-4.rdpui-1.ext-0        #omdb.omnode
192.168.10.21  dev.x2-4.tap-1_ext_0.ctrl-0   #omdb.omnode
192.168.104.2  dev.x2-4.tap-1_ext_0.ext-0    #omdb.omnode
192.168.214.2  dev.x2-4.tap-1_ext_0.ib-0     #omdb.omnode
192.168.204.2  dev.x2-4.tap-1_ext_0.int-0    #omdb.omnode
192.168.10.51  dev.x2-4.tap-4_ext_0.ctrl-0   #omdb.omnode
192.168.104.5  dev.x2-4.tap-4_ext_0.ext-0    #omdb.omnode
192.168.214.5  dev.x2-4.tap-4_ext_0.ib-0     #omdb.omnode
192.168.204.5  dev.x2-4.tap-4_ext_0.int-0    #omdb.omnode
192.168.10.51  dev.x2-4.x2-0.ctrl-0          #omdb.omnode
192.168.104.5  dev.x2-4.x2-0.ext-0           #omdb.omnode
192.168.214.5  dev.x2-4.x2-0.ib-0            #omdb.omnode
192.168.204.5  dev.x2-4.x2-0.int-0           #omdb.omnode
192.168.10.31  dev.x2-4.x2-1.ctrl-0          #omdb.omnode
192.168.104.3  dev.x2-4.x2-1.ext-0           #omdb.omnode
192.168.214.3  dev.x2-4.x2-1.ib-0            #omdb.omnode
192.168.204.3  dev.x2-4.x2-1.int-0           #omdb.omnode
192.168.10.41  dev.x2-4.x2-2.ctrl-0          #omdb.omnode
192.168.104.4  dev.x2-4.x2-2.ext-0           #omdb.omnode
192.168.214.4  dev.x2-4.x2-2.ib-0            #omdb.omnode
192.168.204.4  dev.x2-4.x2-2.int-0           #omdb.omnode
192.168.10.21  dev.x2-4.x2-3.ctrl-0          #omdb.omnode
192.168.104.2  dev.x2-4.x2-3.ext-0           #omdb.omnode
192.168.214.2  dev.x2-4.x2-3.ib-0            #omdb.omnode
192.168.204.2  dev.x2-4.x2-3.int-0           #omdb.omnode
192.168.10.11  dev.x2-4.x2w-1.ctrl-0         #omdb.omnode
192.168.104.1  dev.x2-4.x2w-1.ext-0          #omdb.omnode
# Generated by omcli #omdb.omnode

192.168.10.11  shared.ca-1.easyca-1.ctrl-0   #omdb.omnode
192.168.101.1  shared.ca-1.easyca-1.ext-0    #omdb.omnode
OMHOST
cat /etc/hosts | grep -v "#omdb.omnode" >host
cat omhost >> host
cat host | sudo tee /etc/hosts &> /dev/null
rm -f omhost host
#!/usr/bin/env bash
#
function copy_connector_properties {
cat << 'EOF' >dev.kafkacw-02.worker_properties
bootstrap.servers=dev.x2-4.kafka-1.ext-0:1643,dev.x2-4.kafka-2.ext-0:1650,dev.x2-4.kafka-3.ext-0:1657,dev.x2-4.kafka-4.ext-0:1664
config.storage.replication.factor=1
config.storage.topic=connect-storage-dev.x2-4.kafkacw-1-configs
group.id=dev.x2-4.kafkacw-1
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
listeners=http://dev.x2-4.kafkacw-1.ctrl-0:1683
offset.flush.interval.ms=10000
offset.storage.replication.factor=2
offset.storage.topic=connect-storage-dev.x2-4.kafkacw-1-offsets
plugin.path=/home/kafkausr/kafka/plugins
rest.advertised.host.name=dev.x2-4.kafkacw-1.ctrl-0
rest.advertised.port=1683
status.storage.replication.factor=1
status.storage.topic=connect-storage-dev.x2-4.kafkacw-1-status
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
EOF
cat << 'EOF' >dev.kafkacw-02.connector.json
{
  "name": "dev.x2-4.kafkacw-1-CIDX",
  "config": {
    "aws.access.key.id": "minioadmin",
    "aws.s3.bucket.name": "bucket-dev.x2-4.kafkacw-1",
    "aws.s3.endpoint": "http://dev.x2-4.minio-1.ext-0:1673",
    "aws.s3.path.style.access": "true",
    "aws.s3.region": "us-east-1",
    "aws.secret.access.key": "minioadmin",
    "connector.class": "io.aiven.kafka.connect.s3.AivenKafkaConnectS3SinkConnector",
    "consumer.override.auto.offset.reset": "earliest",
    "consumer.override.enable.auto.commit": "false",
    "errors.log.enable": "true",
    "file.compression.type": "none",
    "file.name.template": "{{topic}}-{{partition:padding=true}}-{{start_offset:padding=true}}",
    "format.class": "io.aiven.kafka.connect.s3.format.json.JsonFormat",
    "format.output.fields": "key,offset,timestamp,value,headers",
    "format.output.type": "jsonl",
    "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "tasks.max": "3",
    "topics.regex": "^(?!(__.*|_schemas|connect-.*)$).*",
    "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"
  }
}
EOF
ln -sfr dev.kafkacw-02.worker_properties worker.properties
}
#
function calculate_CIDX {
export CIDX="0"
CONNECT_URL="http://dev.x2-4.kafkacw-1.ctrl-0:1683"
MAX_NUM=0  # Track the highest number found

# Get the list of connectors
CONNECTORS=$(curl -sS -X GET "$CONNECT_URL/connectors" | jq -r '.[]')

# Iterate over each connector
for CONNECTOR in $CONNECTORS; do
echo "Processing connector: $CONNECTOR"
# Stop the connector
echo "Deleting connector $CONNECTOR..."
curl -sS -X PUT "$CONNECT_URL/connectors/$CONNECTOR/pause"
curl -sS -X DELETE "$CONNECT_URL/connectors/$CONNECTOR"

# Extract the numeric suffix after the last '-'
LAST_PART=$(echo "$CONNECTOR" | grep -o '[^-]*$')

# Ensure it's a number and update MAX_NUM if higher
if [[ "$LAST_PART" =~ ^[0-9]+$ ]]; then
if (( LAST_PART > MAX_NUM )); then
                MAX_NUM=$LAST_PART
fi
else
echo "Warning: Could not extract numeric suffix from $CONNECTOR"
fi
done

# Set CIDX to MAX_NUM + 1 (or 0 if no connectors exist)
export CIDX=$((MAX_NUM + 1))

echo "REPLACING dev.x2-4.kafkacw-1-CIDX with dev.x2-4.kafkacw-1-$CIDX"
sed -i "s/dev.x2-4.kafkacw-1-CIDX/dev.x2-4.kafkacw-1-$CIDX/g" dev.kafkacw-02.connector.json
}
function start_worker {
 set -x
# Create bucket if not there
export KAFKA_HEAP_OPTS="-Xms16G -Xmx16G"
unzip -o /home/kafkausr/confluentinc-kafka-connect-s3-10.6.7.zip -d /home/kafkausr/kafka/plugins


# while :; do
  kafka/bin/connect-distributed.sh -daemon worker.properties 
# Wait up to 30 seconds for port to become available
  timeout 30 bash -c 'until lsof -i :1683 >/dev/null 2>&1; do sleep 1; done'
  if [ $? -eq 0 ]; then
  echo "Connection established on port 1683"
  break
  fi
  pkill -f connect-distributed
  echo "Retrying in 10 seconds..."
   sleep  10
# done
calculate_CIDX
mc stat minio-02/bucket-dev.x2-4.kafkacw-1 &>/dev/null || mc mb minio-02/bucket-dev.x2-4.kafkacw-1
echo "posting connector json after 5 sec sleep"
set -x
sleep 5


# curl -sS -X POST -H "Content-Type: application/json" --data @dev.kafkacw-02.connector.json  http://dev.x2-4.kafkacw-1.ctrl-0:1683/connectors | jq
curl -sS -X POST "http://dev.x2-4.kafkacw-1.ctrl-0:1683/connectors" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "dev.x2-4.kafkacw-1-CIDX",
    "config": {
      "connector.class": "io.confluent.connect.s3.S3SinkConnector",
      "tasks.max": "3",
      "topics.regex": "^(?!(__.*|_schemas|connect-.*)$).*",

      "s3.bucket.name": "bucket-dev.x2-4.kafkacw-1",
      "s3.region": "us-east-1",
      "s3.part.size": "5242880",
      "store.url": "http://dev.x2-4.minio-1.ext-0:1673",
      "s3.path.style.access.enabled": "true",

      "aws.access.key.id": "minioadmin",
      "aws.secret.access.key": "minioadmin",
      "storage.class": "io.confluent.connect.s3.storage.S3Storage",
      "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
      "flush.size": "1000",

      "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
      "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",

      "errors.log.enable": "true",
      "consumer.override.auto.offset.reset": "earliest",
      "consumer.override.enable.auto.commit": "false"
    }
  }' | jq .


} 
#
function stop_worker {
kill -9 $(pidof java) 1>/dev/null 2>/dev/null || { echo "====Was not running"; }
}
function status_worker {
lsof -P -i :1683 && curl -sS http://dev.x2-4.kafkacw-1.ctrl-0:1683/connectors | jq
}
function init_mc {
mc alias set minio-02 http://dev.x2-4.minio-1.ext-0:1673 minioadmin minioadmin --api S3v4 --path auto
}
function format_connector {
# Delete/Create bucket if not there
mc stat minio-02/bucket-dev.x2-4.kafkacw-1 &>/dev/null && mc rb --force minio-02/bucket-dev.x2-4.kafkacw-1; mc mb minio-02/bucket-dev.x2-4.kafkacw-1
}
copy_connector_properties
init_mc
echo "script:info  node:dev.kafkacw-02 omnode:dev.x2-4.kafkacw-1 option:$1 "
case $1 in
     start)
     stop_worker
     start_worker
     ;;
     start_clean)
     stop_worker
     format_connector
     start_worker
     ;;
     stop)
     stop_worker
     ;;
     status)
     status_worker
     ;;
     *)
     ;;
esac
