bin/x2node \
    -node:nj1.sn5.bm \
    -cmd:$'<< \'RUNDOC\'\n
docker kill x2-20
docker rm x2-20
#!/bin/bash
# Generated by dkr
mkdir -p /srv/script/x2-20
chmod g+w /srv/script/x2-20
touch  /srv/script/x2-20/x2-20.start
chmod ugo+wx  /srv/script/x2-20/x2-20.start
ln -sfr /srv/script/x2-20/x2-20.start /srv/script/x2-20/start
tee >/srv/script/x2-20/x2-20.start << \'EOFSCRIPT\'
#
# Script docker/x2/x2.start for x2-20
#
# Replaced run.port22:1551
#!/bin/bash
#!/bin/bash
# mount dirs based on the labels
for i in {1..4}; do
    sudo mkdir -p /mnt/data-${i}
    sudo mount -t xfs -o defaults,noatime,nodiscard -L kafka-data-${i} /mnt/data-${i} || { 
        echo "Mount failed for /mnt/data-${i}. Removing directory..."
        sudo umount /mnt/data-${i} || true
        sudo rmdir /mnt/data-${i} 
    }
    sudo chown x2usr:x2usr /mnt/data-${i}/
done

sed -i \'s/#Port 22/Port 1551/\' /etc/ssh/sshd_config
service ssh restart

echo \'x2usr soft nofile 999999\' | sudo tee -a /etc/security/limits.conf
echo \'x2usr hard nofile 999999\' | sudo tee -a /etc/security/limits.conf
sleep infinity

EOFSCRIPT
#
# Script docker/x2/x2_native.run for x2-20
#
# Replaced run.image:x2
# Replaced run.runname:x2-20
# Replaced run.dserv:dev.x2-20
# Replaced run.nhost:192.168.10.51
# Replaced run.port18184:1547
# Replaced run.port18185:1548
# Replaced run.port1883:1549
# Replaced run.port2080:1550
# Replaced run.port22:1551
# Replaced run.port4222:1552
# Replaced run.port4223:1553
# Replaced run.port443:1554
# Replaced run.port6379:1555
# Replaced run.port6380:1556
# Replaced run.port8883:1557
# Replaced run.port9092:1558
# Replaced run.port9093:1559
docker run \
--restart always \
-h dev.x2-20 \
--add-host dev.x2-20:192.168.10.51 \
--name x2-20 \
--network host \
--privileged \
-p 192.168.10.51:1551:1551 \
-p 192.168.10.51:1547:1547 \
-p 192.168.10.51:1548:1548 \
-p 192.168.10.51:1549:1549 \
-p 192.168.10.51:1550:1550 \
-p 192.168.10.51:1551:1551 \
-p 192.168.10.51:1552:1552 \
-p 192.168.10.51:1553:1553 \
-p 192.168.10.51:1554:1554 \
-p 192.168.10.51:1555:1555 \
-p 192.168.10.51:1556:1556 \
-p 192.168.10.51:1557:1557 \
-p 192.168.10.51:1558:1558 \
-p 192.168.10.51:1559:1559 \
-v /dev/vfio:/dev/vfio \
-v /etc/timezone:/etc/timezone:ro \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/ssmtp:/etc/ssmtp:ro \
-v /srv/script/x2-20:/etc//x2.d/script \
-dit x2

RUNDOC
' \
    -q:Y
