$ bin/dkr  -cmd:'' -clean_run:Y -node:dev.x2-17 -v
dkr.info dctr:x2-17  script:docker/gen/x2-17  dkrcmdarg:generate_dockerbuild/dev.x2-17  comment:"generating dockerbuild script"
bash  -c $'mkdir -p temp/x2 && touch temp/x2/x2.build'
bash  -c $'chmod u+x docker/gen/x2-17'
dkr.info command:generate_dockerbuild 
dkr.report command:generate_dockerbuild  cmd:""  targets:1
bash  -c docker/gen/x2-17
dkr.info image:x2-17 file:temp/docker/x2-17/x2-17.run comment:copying script
dkr.info image:x2-17 file:temp/docker/x2-17/x2-17.build comment:copying script
dkr.info image:x2-17 file:temp/docker/x2-17/Dockerfile comment:copying Dockerfile
dkr.info command:docker_clean_run dctr:x2-17  nodedkr:nj1.sn2.bm  cmd:"docker ps"
dkr.report command:docker_clean_run  cmd:ps  targets:1
bin/x2node  -node:nj1.sn2.bm -cmd:$'<< \'RUNDOC\'\n\
docker kill x2-17\n\
docker rm x2-17\n\
#!/bin/bash\n\
# Generated by dkr\n\
mkdir -p /srv/script/x2-17\n\
chmod g+w /srv/script/x2-17\n\
touch  /srv/script/x2-17/x2-17.start\n\
chmod ugo+wx  /srv/script/x2-17/x2-17.start\n\
ln -sfr /srv/script/x2-17/x2-17.start /srv/script/x2-17/start\n\
tee >/srv/script/x2-17/x2-17.start << \'EOFSCRIPT\'\n\
#\n\
# Script docker/x2/x2.start for x2-17\n\
#\n\
# Replaced run.port22:1512\n\
#!/bin/bash\n\
#!/bin/bash\n\
# mount dirs based on the labels\n\
for i in {1..4}; do\n\
    sudo mkdir -p /mnt/data-${i}\n\
    sudo mount -t xfs -o defaults,noatime,nodiscard -L kafka-data-${i} /mnt/data-${i} || { \n\
        echo "Mount failed for /mnt/data-${i}. Removing directory..."\n\
        sudo umount /mnt/data-${i} || true\n\
        sudo rmdir /mnt/data-${i} \n\
    }\n\
    sudo chown x2usr:x2usr /mnt/data-${i}/\n\
done\n\
\n\
sed -i \'s/#Port 22/Port 1512/\' /etc/ssh/sshd_config\n\
service ssh restart\n\
\necho \'x2usr soft nofile 999999\' | sudo tee -a /etc/security/limits.conf\n\
echo \'x2usr hard nofile 999999\' | sudo tee -a /etc/security/limits.conf\n\
sleep infinity\n\
\n\
EOFSCRIPT\n\
#\n\
# Script docker/x2/x2_native.run for x2-17\n\
#\n\
# Replaced run.image:x2\n\
# Replaced run.runname:x2-17\n\
# Replaced run.dserv:dev.x2-17\n\
# Replaced run.nhost:192.168.10.21\n\
# Replaced run.port18184:1508\n\
# Replaced run.port18185:1509\n\
# Replaced run.port1883:1510\n\
# Replaced run.port2080:1511\n\
# Replaced run.port22:1512\n\
# Replaced run.port4222:1513\n\
# Replaced run.port4223:1514\n\
# Replaced run.port443:1515\n\
# Replaced run.port6379:1516\n\
# Replaced run.port6380:1517\n\
# Replaced run.port8883:1518\n\
# Replaced run.port9092:1519\n\
# Replaced run.port9093:1520\n\
docker run \\\n\
--restart always \\\n\
-h dev.x2-17 \\\n\
--add-host dev.x2-17:192.168.10.21 \\\n\
--name x2-17 \\\n\
--network host \\\n\
--privileged \\\n\
-p 192.168.10.21:1512:1512 \\\n\
-p 192.168.10.21:1508:1508 \\\n\
-p 192.168.10.21:1509:1509 \\\n\
-p 192.168.10.21:1510:1510 \\\n\
-p 192.168.10.21:1511:1511 \\\n\
-p 192.168.10.21:1512:1512 \\\n\
-p 192.168.10.21:1513:1513 \\\n\
-p 192.168.10.21:1514:1514 \\\n\
-p 192.168.10.21:1515:1515 \\\n\
-p 192.168.10.21:1516:1516 \\\n\
-p 192.168.10.21:1517:1517 \\\n\
-p 192.168.10.21:1518:1518 \\\n\
-p 192.168.10.21:1519:1519 \\\n\
-p 192.168.10.21:1520:1520 \\\n\
-v /dev/vfio:/dev/vfio \\\n\
-v /etc/timezone:/etc/timezone:ro \\\n\
-v /etc/localtime:/etc/localtime:ro \\\n\
-v /etc/ssmtp:/etc/ssmtp:ro \\\n\
-v /srv/script/x2-17:/etc//x2.d/script \\\n\
-dit x2\n\
\n\
RUNDOC\n' -q:Y
bin/x2node  -node:nj1.sn2.bm -cmd:'docker ps' -q:Y
bin/x2node  -node:nj1.sn2.bm -cmd:$'<< \'RUNDOC\'\n\
docker kill x2-17\n\
docker rm x2-17\n\
#!/bin/bash\n\
# Generated by dkr\n\
mkdir -p /srv/script/x2-17\n\
chmod g+w /srv/script/x2-17\n\
touch  /srv/script/x2-17/x2-17.start\n\
chmod ugo+wx  /srv/script/x2-17/x2-17.start\n\
ln -sfr /srv/script/x2-17/x2-17.start /srv/script/x2-17/start\n\
tee >/srv/script/x2-17/x2-17.start << \'EOFSCRIPT\'\n\
#\n\
# Script docker/x2/x2.start for x2-17\n\
#\n\
# Replaced run.port22:1512\n\
#!/bin/bash\n\
#!/bin/bash\n\
# mount dirs based on the labels\n\
for i in {1..4}; do\n\
    sudo mkdir -p /mnt/data-${i}\n\
    sudo mount -t xfs -o defaults,noatime,nodiscard -L kafka-data-${i} /mnt/data-${i} || { \n\
        echo "Mount failed for /mnt/data-${i}. Removing directory..."\n\
        sudo umount /mnt/data-${i} || true\n\
        sudo rmdir /mnt/data-${i} \n\
    }\n\
    sudo chown x2usr:x2usr /mnt/data-${i}/\n\
done\n\
\n\
sed -i \'s/#Port 22/Port 1512/\' /etc/ssh/sshd_config\n\
service ssh restart\n\
\necho \'x2usr soft nofile 999999\' | sudo tee -a /etc/security/limits.conf\n\
echo \'x2usr hard nofile 999999\' | sudo tee -a /etc/security/limits.conf\n\
sleep infinity\n\
\n\
EOFSCRIPT\n\
#\n\
# Script docker/x2/x2_native.run for x2-17\n\
#\n\
# Replaced run.image:x2\n\
# Replaced run.runname:x2-17\n\
# Replaced run.dserv:dev.x2-17\n\
# Replaced run.nhost:192.168.10.21\n\
# Replaced run.port18184:1508\n\
# Replaced run.port18185:1509\n\
# Replaced run.port1883:1510\n\
# Replaced run.port2080:1511\n\
# Replaced run.port22:1512\n\
# Replaced run.port4222:1513\n\
# Replaced run.port4223:1514\n\
# Replaced run.port443:1515\n\
# Replaced run.port6379:1516\n\
# Replaced run.port6380:1517\n\
# Replaced run.port8883:1518\n\
# Replaced run.port9092:1519\n\
# Replaced run.port9093:1520\n\
docker run \\\n\
--restart always \\\n\
-h dev.x2-17 \\\n\
--add-host dev.x2-17:192.168.10.21 \\\n\
--name x2-17 \\\n\
--network host \\\n\
--privileged \\\n\
-p 192.168.10.21:1512:1512 \\\n\
-p 192.168.10.21:1508:1508 \\\n\
-p 192.168.10.21:1509:1509 \\\n\
-p 192.168.10.21:1510:1510 \\\n\
-p 192.168.10.21:1511:1511 \\\n\
-p 192.168.10.21:1512:1512 \\\n\
-p 192.168.10.21:1513:1513 \\\n\
-p 192.168.10.21:1514:1514 \\\n\
-p 192.168.10.21:1515:1515 \\\n\
-p 192.168.10.21:1516:1516 \\\n\
-p 192.168.10.21:1517:1517 \\\n\
-p 192.168.10.21:1518:1518 \\\n\
-p 192.168.10.21:1519:1519 \\\n\
-p 192.168.10.21:1520:1520 \\\n\
-v /dev/vfio:/dev/vfio \\\n\
-v /etc/timezone:/etc/timezone:ro \\\n\
-v /etc/localtime:/etc/localtime:ro \\\n\
-v /etc/ssmtp:/etc/ssmtp:ro \\\n\
-v /srv/script/x2-17:/etc//x2.d/script \\\n\
-dit x2\n\
\n\
RUNDOC\n' -q:Y

bin/x2node  -node:nj1.sn2.bm -cmd:'docker ps' -q:Y

[0 May 15 22:15:45] avorovich@nj1.sn1.avorovich:~/arnd 