#
# Generated by omcli
# Cluster:dev.ak-8 Node:dev.ak-8.kafkaw-2
#
cat << 'HOSTS' > omhosts
# Generated by omcli

192.168.10.21  dev.kafka-01
192.168.10.21  dev.ak-8.kafka-1.ctrl
192.168.108.2  dev.ak-8.kafka-1.ext
192.168.218.2  dev.ak-8.kafka-1.ib
192.168.208.2  dev.ak-8.kafka-1.int
192.168.10.31  dev.kafka-02
192.168.10.31  dev.ak-8.kafka-2.ctrl
192.168.108.3  dev.ak-8.kafka-2.ext
192.168.218.3  dev.ak-8.kafka-2.ib
192.168.208.3  dev.ak-8.kafka-2.int
192.168.10.41  dev.kafka-03
192.168.10.41  dev.ak-8.kafka-3.ctrl
192.168.108.4  dev.ak-8.kafka-3.ext
192.168.218.4  dev.ak-8.kafka-3.ib
192.168.208.4  dev.ak-8.kafka-3.int
192.168.10.51  dev.kafka-04
192.168.10.51  dev.ak-8.kafka-4.ctrl
192.168.108.5  dev.ak-8.kafka-4.ext
192.168.218.5  dev.ak-8.kafka-4.ib
192.168.208.5  dev.ak-8.kafka-4.int
192.168.10.11  dev.kafkaui-1
192.168.10.11  dev.ak-8.kafkaui-1.ctrl
192.168.108.1  dev.ak-8.kafkaui-1.ext
192.168.10.61  dev.kafkaw-08
192.168.10.61  dev.ak-8.kafkaw-1.ctrl
192.168.108.6  dev.ak-8.kafkaw-1.ext
192.168.10.71  dev.kafkaw-16
192.168.10.71  dev.ak-8.kafkaw-2.ctrl
192.168.108.7  dev.ak-8.kafkaw-2.ext
192.168.10.11  dev.rdpui-1
192.168.10.11  dev.ak-8.rdpui-1.ctrl
192.168.108.1  dev.ak-8.rdpui-1.ext
192.168.10.11  dev.x2w-01
192.168.10.11  dev.ak-8.x2w-1.ctrl
192.168.108.1  dev.ak-8.x2w-1.ext
HOSTS
cat omhosts | sudo tee /etc/hosts &> /dev/null
#!/usr/bin/env bash
#!/usr/bin/env bash
#
cat << 'EOF' >workers.yaml
workers:
  - http://dev.ak-8.kafkaw-1.ctrl:1118
  - http://dev.ak-8.kafkaw-2.ctrl:1160
EOF
#
function configure_driver {
DRIVER_FILES=$(ls -1 /opt/benchmark/driver-kafka/*.yaml)
for FILE in $DRIVER_FILES; do
  sed -i "s/^  bootstrap.servers=.*$/  bootstrap.servers=dev.ak-8.kafka-1.ext:1031,dev.ak-8.kafka-2.ext:1039,dev.ak-8.kafka-3.ext:1043,dev.ak-8.kafka-4.ext:1047/g" $FILE
done
}
#
function configure_jms {
JMS_FILES=$(ls -1 /opt/benchmark/driver-jms/*.yaml)
for FILE in $JMS_FILES; do
  sed -i "s/^  bootstrap.servers=.*$/  bootstrap.servers=dev.ak-8.kafka-1.ext:1031,dev.ak-8.kafka-2.ext:1039,dev.ak-8.kafka-3.ext:1043,dev.ak-8.kafka-4.ext:1047/g" $FILE
  sed -i "s/localhost:9092/dev.ak-8.kafka-1.ext:1031,dev.ak-8.kafka-2.ext:1039,dev.ak-8.kafka-3.ext:1043,dev.ak-8.kafka-4.ext:1047/g" $FILE
done
}
#
function configure_worker_memory {
sed -i 's/^JVM_MEM=.*$/JVM_MEM=" -Xms24G -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+ParallelRefProcEnabled -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -XX:+AlwaysPreTouch -XX:ZAllocationSpikeTolerance=5"/g' /opt/benchmark/bin/benchmark-worker
}
#
function configure_benchmark_memory {
sed -i 's/^JVM_MEM=.*$/JVM_MEM=" -Xmx4G"/g' /opt/benchmark/bin/benchmark
}
#
function start_kafka_worker {
  configure_driver
  configure_jms
  configure_worker_memory
  configure_benchmark_memory
  rm -f benchmark-worker.log
until nohup bin/benchmark-worker --port 1160 --stats-port 1161 >~/kafka_worker.log 2>&1 &
  sleep 1
  pgrep java >/dev/null; do
  echo "Benchmark worker failed to start. Retrying..."
done
for i in {1..60}; do lsof -i :1160 >/dev/null && { echo; echo $(hostname):success; exit 0; } || echo -n .; sleep 1; done;
echo; echo $(hostname):failed; exit 1
}
#
#
#
function stop_kafka_worker {
  killall java 1>/dev/null 2>/dev/null
}
#
#
function status_kafka_worker {
  lsof -P -i :1160
}
#
#
echo "script:info  node:dev.kafkaw-16 omnode:dev.ak-8.kafkaw-2 option:$1 "
case $1 in
     start | start_clean)
     stop_kafka_worker
     start_kafka_worker
     ;;
     stop)
     stop_kafka_worker
     ;;
     status)
     status_kafka_worker
     ;;
     *)
     ;;
esac
